### ISSUE TITLE
Attempting to change access mechanism error on iOS

### ISSUE THREAD

**Issue by jimmyvdberg** [aurelia/pal-browser#19]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
iOS 8, iPad Air 2

* **Browser:**
Safari and Chrome

* **Language:**
TypeScript 2.1.1

**Current behavior:**
I'm getting an error since the new update to 1.2.0 (#18) on iOS:
`vendor-bundle.js:formatted:10095TypeError: Attempting to change access mechanism for an unconfigurable property.`

I get this error on `Function.prototype` in the following code sample:

```
    if ("undefined" == typeof FEATURE_NO_IE) {
        (function() {}
        ).name || Object.defineProperty(Function.prototype, "name", {
            get: function() {
                var e = this.toString().match(/^\s*function\s*(\S*)\s*\(/)[1];
                return Object.defineProperty(this, "name", {
                    value: e
                }),
                e
            }
        })
    }
```

To reproduce you can create a new project ussing the aurelia-cli. It will include version 1.2.0 and this issue.

**Expected/desired behavior:**

* **What is the expected behavior?**
When switching back to the previous version (1.1.0) it is still working. Could you guys have a look at it and fix the issue?

**Comment by doubleaa93** [comment]
I was just about to post this I have the same problem rolling back to 1.1.0 fixes the problem.

**Comment by EisenbergEffect** [comment]
@jods4 Can you look into this. Looks like the change caused a regression.

**Comment by jods4** [comment]
Here's a guess but I'll need help to confirm.

I think the code above does not properly detect `Function.prototype.name` support because its test:
```js
(function() {}).name
```
Will be false, since that function has no name (empty string).

But the interesting part is that this is not the code we distribute. What we distribute is this:
```js
function test() {}
if (!test.name) { ... }
```
Which should work. The code that doesn't work above is surely the result of a minimization pass, which often discards the name of functions and classes as unimportant. I think that we don't want to keep all function names just for that so we need a workaround.

The interesting part is that I did not change this test in 1.2, it's always been like that.
What changed is that in 1.1 the  `function test() {}` was inside a local function, while in 1.2 it's at root of module scope. It would be interesting if you could confirm that the minimizer preserves the function name when it's nested and generates the code above when it's not.

Maybe we should change that feature detection to something more robust? 
Couldn't we test `'name' in Function.prototype`?

**Comment by jods4** [comment]
OK I did some additional tests.

I can confirm that for no apparent reason, Uglify and Babili both kept the local function and its name when it was declared nested inside an auxiliary function, but minimize the same fragment of code more aggressively in 1.2.

To fix it I would suggest that we change the `if (!test.name)` feature detection to either `if (test.name === undefined)` (to stay close to existing code) or `if ('name' in Function.prototype)` (seems better to me?).

Unfortunately I do not have access to a Mac, so I would need help to test this before we publish it. The funny thing is that `Function.prototype.name` should be configurable according to MDN and the code above does run anyway (I tested in Edge and Firefox). The fact that it crashes because `name` is unconfigurable seems to be a bug in iOS.

@jimmyvdberg or @doubleaa93, could you manually edit your local `aurelia-pal-browser` source to change `if (!test.name)` to `if (test.name === undefined)` and confirm it works before we I do a PR and we publish a fix?

**Comment by jods4** [comment]
As this is important I have already prepared a PR with the fix: #20.
I have been unable to test it, though.

**Comment by jimmyvdberg** [comment]
@jods4 I changed the code as you said from `if (!test.name)` to `if (test.name === undefined)`. And it now works on iOS! 👍 I also did a quick test on some Android and Windows devices, and they also work.

The minified file now looks like this:
```
    if ("undefined" == typeof FEATURE_NO_IE) {
        void 0 === function() {}
        .name && Object.defineProperty(Function.prototype, "name", {
            get: function() {
                var e = this.toString().match(/^\s*function\s*(\S*)\s*\(/)[1];
                return Object.defineProperty(this, "name", {
                    value: e
                }),
                e
            }
        })
```

**Comment by jods4** [comment]
wow those minifiers sure know their JS syntax well.
I was surprised because this is invalid: `function() {}.name`
But it turns out that in an expression location like `void 0 === function() {}.name` it's fine!

@EisenbergEffect Should we proceed with merging and publishing PR #20 ?

**Comment by EisenbergEffect** [comment]
I'll get this done today.
